---
title: "R Notebook"
output: html_notebook
---


```{r}
#         SMALL PERMUTATION DATA IMPORT
setwd("U:/FTDC-IrwinLab/TMA Take 2/AT8 TMA results/Run 1 Slide 1")    # Set working directory

r1.s1.p1.small <-read_excel("AT8-DAB-5_29_19.p1.xlsx")  # Small Permutation 1
r1.s1.p2.small <-read_excel("AT8-DAB-5_29_19.p2.xlsx")  # Small Permutation 2
r1.s1.p3.small <-read_excel("AT8-DAB-5_29_19.p3.xlsx")  # Small Permutation 3
r1.s1.p4.small <-read_excel("AT8-DAB-5_29_19.p4.xlsx")  # Small Permutation 4
r1.s1.p5.small <-read_excel("AT8-DAB-5_29_19.p5.xlsx")  # Small Permutation 5



#       Create function to clean TMA core permutation data to yield coreID, OD, and %AO
core_permutation_cleaning_small<-function(df){
  cores <- df[,c(1)]                   # Creates dataframe with containing Core Names
  df<- df[,seq(12, ncol(df),6)]  # removes unnessary columns - only keeps %AO of ROI
  df<-cbind(cores,df) # Binds column with names
  df<-reshape2::melt(df, idvars = "Name")
  df$variable<-as.character(df$variable)
  df$OD<- substr(df$variable, 52,58)
  df$OD<-gsub("[)]","0",df$OD)
  df<- df[order(df$Name,df$OD),]
  df<-df[,-c(2)]
  df<- df[,c("Name","OD","value")]
  
  
  return(df)

}



r1.s1.p1.small_long<-core_permutation_cleaning_small(r1.s1.p1.small)
r1.s1.p2.small_long<-core_permutation_cleaning_small(r1.s1.p2.small)
r1.s1.p3.small_long<-core_permutation_cleaning_small(r1.s1.p3.small)
r1.s1.p4.small_long<-core_permutation_cleaning_small(r1.s1.p4.small)
r1.s1.p5.small_long<-core_permutation_cleaning_small(r1.s1.p5.small)


######################
# Create plot of %AO by OD Colored by Core
r2.s2.lg_long<- ggplot(r2.s2.p1.large_long, aes(y=value, x=OD, color=Name, group=Name)) + 
  geom_point(aes(color = Name)) +
  geom_line()
r2.s2.lg_long + theme(axis.text.x = element_text(angle = 45)) + 
  labs(y="%AO")+
  facet_grid(, group=Name)


graph_AO_OD<- function(df){
  run.slide.p.sz.dir<- ggplot(df, aes(y=value, x=OD, color=Name, group=Name)) + 
  geom_point(aes(color = Name)) +
  geom_line()
run.slide.p.sz.dir + theme(axis.text.x = element_text(angle = 45)) + 
  labs(y="%AO")
}

recursive_AO_differences<-function(df){
  empty.cell<- NA
  differences<-data.frame(abs(diff(df$value)))
  df$differences <- rbind(c(NA),differences)
  x<-df$differences
  df<-cbind(df,x)
  df<-df[,-c(4)]
  colnames(df)<-c("Core","OD","AO","Diff")
  df<-reshape(df,idvar="OD", timevar = "Core", direction = "wide")
  df<-data.frame(df[-c(1),])
  return(df)
}


r1.s1.p1.small_wide<-recursive_AO_differences(r1.s1.p1.small_long)
r1.s1.p2.small_wide<-recursive_AO_differences(r1.s1.p2.small_long)
r1.s1.p3.small_wide<-recursive_AO_differences(r1.s1.p3.small_long)
r1.s1.p4.small_wide<-recursive_AO_differences(r1.s1.p4.small_long)
r1.s1.p5.small_wide<-recursive_AO_differences(r1.s1.p5.small_long)

averaging_AO_and_differences<-function(wide_df){
AO.Avg<-wide_df %>%
    select(seq(from=2, to=ncol(.), by=2)) %>%
    transmute(AO.Avg =(rowSums(.))/12)
Diff.Avg<-wide_df %>%
  select(seq(from=3, to=ncol(.), by=2)) %>%
  transmute(Diff.Avg =(rowSums(.))/12)
avgs<-cbind(AO.Avg,Diff.Avg)
wide_df_avg<-cbind(wide_df,avgs)


return(wide_df_avg)

}



avg.r1.s1.p1.small_wide<-averaging_AO_and_differences(r1.s1.p1.small_wide)
avg.r1.s1.p2.small_wide<-averaging_AO_and_differences(r1.s1.p2.small_wide)
avg.r1.s1.p3.small_wide<-averaging_AO_and_differences(r1.s1.p3.small_wide)
avg.r1.s1.p4.small_wide<-averaging_AO_and_differences(r1.s1.p4.small_wide)
avg.r1.s1.p5.small_wide<-averaging_AO_and_differences(r1.s1.p5.small_wide)
avg.r1.s1.p5.small_wide<-avg.r1.s1.p5.small_wide[2:75,]
write.csv(avg.r1.s1.p1.small_wide, "avg.r1.s1.p1.small_wide.csv" )
write.csv(avg.r1.s1.p2.small_wide, "avg.r1.s1.p2.small_wide.csv" )
write.csv(avg.r1.s1.p3.small_wide, "avg.r1.s1.p3.small_wide.csv" )
write.csv(avg.r1.s1.p4.small_wide, "avg.r1.s1.p4.small_wide.csv" )
write.csv(avg.r1.s1.p5.small_wide, "avg.r1.s1.p5.small_wide.csv" )

all.r1.s2<-bind(avg.r1.s1.p1.small_wide,avg.r1.s1.p2.small_wide,avg.r1.s1.p3.small_wide,avg.r1.s1.p4.small_wide,avg.r1.s1.p5.small_wide)

```

```{r}
#         SMALL PERMUTATION DATA IMPORT
setwd("U:/FTDC-IrwinLab/TMA Take 2/AT8 TMA results/Run 1 Slide 2")    # Set working directory

r1.s2.p1.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 1_AVG.xlsx")  # Small Permutation 1
r1.s2.p2.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 2_AVG.xlsx")  # Small Permutation 2
r1.s2.p3.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 3_AVG.xlsx")  # Small Permutation 3
r1.s2.p4.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 4_AVG.xlsx")  # Small Permutation 4
r1.s2.p5.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 5_AVG.xlsx")  # Small Permutation 5


r1.s2.p1.small_long<-core_permutation_cleaning_small(r1.s2.p1.small)
r1.s2.p2.small_long<-core_permutation_cleaning_small(r1.s2.p2.small)
r1.s2.p3.small_long<-core_permutation_cleaning_small(r1.s2.p3.small)
r1.s2.p4.small_long<-core_permutation_cleaning_small(r1.s2.p4.small)
r1.s2.p5.small_long<-core_permutation_cleaning_small(r1.s2.p5.small)


r1.s2.p1.small_wide<-recursive_AO_differences(r1.s2.p1.small_long)
r1.s2.p2.small_wide<-recursive_AO_differences(r1.s2.p2.small_long)
r1.s2.p3.small_wide<-recursive_AO_differences(r1.s2.p3.small_long)
r1.s2.p4.small_wide<-recursive_AO_differences(r1.s2.p4.small_long)
r1.s2.p5.small_wide<-recursive_AO_differences(r1.s2.p5.small_long)



avg.r1.s2.p1.small_wide<-averaging_AO_and_differences(r1.s2.p1.small_wide)
avg.r1.s2.p2.small_wide<-averaging_AO_and_differences(r1.s2.p2.small_wide)
avg.r1.s2.p3.small_wide<-averaging_AO_and_differences(r1.s2.p3.small_wide)
avg.r1.s2.p4.small_wide<-averaging_AO_and_differences(r1.s2.p4.small_wide)
avg.r1.s2.p5.small_wide<-averaging_AO_and_differences(r1.s2.p5.small_wide)
write.csv(avg.r1.s2.p1.small_wide, "avg.r1.s1.p1.small_wide.csv" )
write.csv(avg.r1.s2.p2.small_wide, "avg.r1.s1.p2.small_wide.csv" )
write.csv(avg.r1.s2.p3.small_wide, "avg.r1.s1.p3.small_wide.csv" )
write.csv(avg.r1.s2.p4.small_wide, "avg.r1.s1.p4.small_wide.csv" )
write.csv(avg.r1.s2.p5.small_wide, "avg.r1.s1.p5.small_wide.csv" )
```

```{r}
#         SMALL PERMUTATION DATA IMPORT
setwd("U:/FTDC-IrwinLab/TMA Take 2/AT8 TMA results/Run 1 Slide 2")    # Set working directory

r1.s2.p1.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 1_AVG.xlsx")  # Small Permutation 1
r1.s2.p2.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 2_AVG.xlsx")  # Small Permutation 2
r1.s2.p3.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 3_AVG.xlsx")  # Small Permutation 3
r1.s2.p4.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 4_AVG.xlsx")  # Small Permutation 4
r1.s2.p5.small <-read_excel("AT8-DAB-5_29_19_11.06.2019_11.13.13_Permutation 5_AVG.xlsx")  # Small Permutation 5


r1.s2.p1.small_long<-core_permutation_cleaning_small(r1.s2.p1.small)
r1.s2.p2.small_long<-core_permutation_cleaning_small(r1.s2.p2.small)
r1.s2.p3.small_long<-core_permutation_cleaning_small(r1.s2.p3.small)
r1.s2.p4.small_long<-core_permutation_cleaning_small(r1.s2.p4.small)
r1.s2.p5.small_long<-core_permutation_cleaning_small(r1.s2.p5.small)


r1.s2.p1.small_wide<-recursive_AO_differences(r1.s2.p1.small_long)
r1.s2.p2.small_wide<-recursive_AO_differences(r1.s2.p2.small_long)
r1.s2.p3.small_wide<-recursive_AO_differences(r1.s2.p3.small_long)
r1.s2.p4.small_wide<-recursive_AO_differences(r1.s2.p4.small_long)
r1.s2.p5.small_wide<-recursive_AO_differences(r1.s2.p5.small_long)



avg.r1.s2.p1.small_wide<-averaging_AO_and_differences(r1.s2.p1.small_wide)
avg.r1.s2.p2.small_wide<-averaging_AO_and_differences(r1.s2.p2.small_wide)
avg.r1.s2.p3.small_wide<-averaging_AO_and_differences(r1.s2.p3.small_wide)
avg.r1.s2.p4.small_wide<-averaging_AO_and_differences(r1.s2.p4.small_wide)
avg.r1.s2.p5.small_wide<-averaging_AO_and_differences(r1.s2.p5.small_wide)
write.csv(avg.r1.s2.p1.small_wide, "avg.r1.s1.p1.small_wide.csv" )
write.csv(avg.r1.s2.p2.small_wide, "avg.r1.s1.p2.small_wide.csv" )
write.csv(avg.r1.s2.p3.small_wide, "avg.r1.s1.p3.small_wide.csv" )
write.csv(avg.r1.s2.p4.small_wide, "avg.r1.s1.p4.small_wide.csv" )
write.csv(avg.r1.s2.p5.small_wide, "avg.r1.s1.p5.small_wide.csv" )
```

